check-shell-lint:
  services:
    - image:e3
  stage: build
  script:
      - shellcheck -S warning **/*.sh

check-python-lint:
  services:
    - image:e3
  stage: build
  script:
      - black .

build-doc:
  services:
    - image:ada-trainings
  stage: build
  script:
      - make -C doc html SPHINXOPTS="-W --keep-going -n"
