stages:
    - test
    - build

check_syntax:
  stage: test
  services:
    - image:lint

  script:
    - autolint --check --output-code-climate-report=code_quality_report.json .

  allow_failure: true

  artifacts:
    when: always
    reports:
      codequality: code_quality_report.json

build-doc:
  services:
    - image:ada-trainings
  stage: build
  script:
      - make -C doc html SPHINXOPTS="-W --keep-going -n"
