SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
include  $(SELF_DIR)Makefile.env

CUDA_HOST=x86_64-linux

example_build:
	gprbuild -f -Xcuda_host=$(CUDA_HOST) -Xgpu_arch=$(GPU_ARCH) -P device -largs -mcpu=$(GPU_ARCH)
	gprbuild -f -Xcuda_host=$(CUDA_HOST) -P host -largs $(CURDIR)/lib/*.fatbin.o
